### ISSUE TITLE
Can not extract video

### ISSUE THREAD

**Issue by NguyenKhacPhuc** [maxrave-dev/kotlin-youtubeExtractor#1]
Hi, I followed the guide but the ytFiles is always null and can not extract any video. Any ideas? Thanks

**Comment by maxrave-dev** [comment]
Can you send me more information, what video did you extract (YouTube URL...)?
Turn on LOGGING in YTExtractor and send me your LOG

**Comment by NguyenKhacPhuc** [comment]
Yeah sure, here how I use it 
<img width="792" alt="image" src="https://github.com/maxrave-dev/kotlin-youtubeExtractor/assets/44175326/53cf1422-fee7-4e99-b73c-3fcc54e44019">
here is error log 
<img width="1159" alt="image" src="https://github.com/maxrave-dev/kotlin-youtubeExtractor/assets/44175326/17502a83-5d6a-480e-ad6e-546057bac6b4">
Thanks for quick support

**Comment by NguyenKhacPhuc** [comment]
Acutally, I have used the original lib of Harald but it is getting this error also, might be the error is from Harald module
https://github.com/HaarigerHarald/android-youtubeExtractor/issues/237

Edit1: I try include to see all the log, seems like it is from Harald module, the same with the one I attached above
<img width="847" alt="image" src="https://github.com/maxrave-dev/kotlin-youtubeExtractor/assets/44175326/513cf1bb-e8b2-41b9-accd-05f656548c03">

**Comment by maxrave-dev** [comment]
Did you have permission to access internet in Manifest?

**Comment by maxrave-dev** [comment]
> Acutally, I have used the original lib of Harald but it is getting this error also, might be the error is from Harald module [HaarigerHarald/android-youtubeExtractor#237](https://github.com/HaarigerHarald/android-youtubeExtractor/issues/237)
> 
> Edit1: I try include to see all the log, seems like it is from Harald module, the same with the one I attached above <img alt="image" width="847" src="https://user-images.githubusercontent.com/44175326/255154971-513cf1bb-e8b2-41b9-accd-05f656548c03.png">

Your app causes this issue doesn't have INTERNET permission or your Internet doesn't work.

**Comment by maxrave-dev** [comment]
Try adding this to your AndroidManifest.xml file, right before `</manifest>`

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by NguyenKhacPhuc** [comment]
Yes, already have the permission, seems like it is because of my network, I was used wifi Hotspot from my mobile and it caused that error, after change it to normal wifi, it works fine. Thanks
